using UnityEngine;

// Periodically spawns Pothole prefabs on the road grid.
// Attach this to the PotholeSpawner GameObject.
public class PotholeSpawner : MonoBehaviour
{
    [Header("Prefab")]
    public GameObject potholePrefab; // Assigned automatically by the city builder.

    [Header("Spawning")]
    public float spawnInterval = 10f; // Seconds between each new pothole.
    public float spawnY = 0.04f;      // Y height — sits at road surface level.

    private float timer = 0f;

    // Road zones: (center X, center Z, half-length X, half-length Z)
    // These match the road positions generated by NightShiftCityBuilder.
    // Potholes spawn within these rectangles so they appear on roads.
    private static readonly (float cx, float cz, float hx, float hz)[] roadZones =
    {
        ( 0f,   0f, 21f, 1.7f), // EW main road
        ( 0f,   0f, 1.7f, 21f), // NS main road
        ( 0f,  15f, 21f, 1.2f), // EW north road
        ( 0f, -15f, 21f, 1.2f), // EW south road
        (15f,   0f, 1.2f, 21f), // NS east road
        (-15f,  0f, 1.2f, 21f), // NS west road
    };

    void Start()
    {
        // Spawn one pothole at startup so RepairBots have something to do immediately.
        SpawnPothole();
    }

    void Update()
    {
        timer += Time.deltaTime;
        if (timer >= spawnInterval)
        {
            SpawnPothole();
            timer = 0f;
        }
    }

    void SpawnPothole()
    {
        if (potholePrefab == null)
        {
            Debug.LogError("PotholeSpawner: potholePrefab is not assigned!");
            return;
        }

        // Pick a random road zone and a random point within it.
        var zone = roadZones[Random.Range(0, roadZones.Length)];
        float x = zone.cx + Random.Range(-zone.hx, zone.hx);
        float z = zone.cz + Random.Range(-zone.hz, zone.hz);
        Vector3 pos = new Vector3(x, spawnY, z);

        GameObject obj = Instantiate(potholePrefab, pos, Quaternion.identity);
        obj.name = "Pothole";
        obj.tag  = "Pothole";

        PotholeItem item = obj.GetComponent<PotholeItem>();
        if (item == null) item = obj.AddComponent<PotholeItem>();
        item.isClaimed = false;

        if (CityManager.Instance != null)
            CityManager.Instance.RegisterPotholeSpawned();

        Debug.Log("Spawned pothole at " + pos);
    }
}
